### PR TITLE
Add scientific package benchmarking project proposal

### PR DESCRIPTION
**Pull request by CDLuminate**
This project proposal originates from https://wiki.debian.org/SummerOfCode2017/Projects/Benchmarking

Note, mentors and contacts are to be added.

Is it acceptable?

### CODE REVIEW

**Comment by mr-c** [comment]
Looks good, it needs mentors -- adding a bioinformatics slant would also be useful.

**Comment by kblin** [comment]
Yes, please add at least two mentors.

**Comment by CDLuminate** [comment]
I have got only one mentor yet. Will the student application deadline (24 hours later) block such an in-progress proposal?

**Comment by CDLuminate** [comment]
I've got two mentors for this project. Updates are force merged into the original commit.

**Comment by CDLuminate** [comment]
Well ... The another mentor didn't register ... so I'm changing the mentor list back to 1 mentor...

**Pull request closed without merging**
