### PR TITLE
BioJS Frontend Proposal

### PR DESCRIPTION
**Pull request by DennisSchwartz**
@rowlandm @yochannah this is the frontend proposal.

### CODE REVIEW

**Comment by rowlandm** [comment]
Looks good. Thanks Dennis!

**Comment by kblin** [comment]
Merged manually after resolving merge conflicts as 709c5f5

**Comment by kblin** [comment]
whyever 709c5f5 is not a link. Looking at you here, github.

**Comment by DennisSchwartz** [comment]
@kblin Thanks! Was about to look into fixing the conflicts myself :)

**Comment by kblin** [comment]
Ah, no worries. This kind is easy, because all you need to do is to paste the text at the correct location. It's not code. :)

**Pull request closed without merging**
