### PR TITLE
GeneNetwork/Biodiallance project added

### PR DESCRIPTION
**Pull request by pjotrp**

### CODE REVIEW

**Comment by peterjc** [comment]
I'm not sure it makes sense to list the Biodiallance mailing list as a third mentor - but good to link to that as a relevant way to interact with the community.

**Comment by pjotrp** [comment]
We will get an individual too. Still in discussion. Anyone of the JS community want to pitch in?

**Comment by kblin** [comment]
I agree with @peterjc here, maybe list them as contact, and then just do another pull request once you have an individual mentor from Biodiallance

**Comment by pjotrp** [comment]
Ok, I removed the ML. Please merge this request so studentes can actually see the proposal. The biodiallance people are on board, I'll forward the E-mail to you guys.

**Pull request merged**
